name: MinecraftManhunt
version: 1.4.1
main: com.yoonicode.minecraftmanhunt.PluginMain
api-version: 1.16
commands:
  hunter:
    description: Register a player as a manhunt Hunter.
    usage: /hunter <target>
    permission: minecraftmanhunt.hunter
  speedrunner:
    description: Register a player as a manhunt Speedrunner.
    usage: /speedrunner <target>
    permission: minecraftmanhunt.speedrunner
  spectator:
    description: Register a player as a manhunt Spectator.
    usage: /spectator <target>
    permission: minecraftmanhunt.spectator
  clearteams:
    description: Clears teams and removes Discord roles.
    usage: /clearteams
    permission: minecraftmanhunt.clearteams
  start:
    description: Start the Manhunt game.
    usage: /start
    permission: minecraftmanhunt.start
  end:
    description: Stops the Manhunt game.
    usage: /end
    permission: minecraftmanhunt.end
  setheadstart:
    description: Sets the headStartDuration field in plugin config, in seconds.
    usage: /setheadstart <seconds>
    permission: minecraftmanhunt.config
  compass:
    description: Use to obtain a compass.
    usage: /compass
    permission: minecraftmanhunt.compass
  music:
    description: Play a music track.
    usage: /music <auto|stop|list|forceupdate|track name>
    permission: minecraftmanhunt.music